/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/airplane/model.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['map_FlyShip_001.001']} position={[-0.138, 0.673, -0.033]} rotation={[-1.58, 0, 1.57]} />
      <mesh geometry={nodes.Object_2001.geometry} material={materials['map_FlyShip_001.001']} position={[-1.9, -0.49, -1.646]} rotation={[-1.58, 0, 1.57]} />
      <mesh geometry={nodes.Object_2002.geometry} material={materials['map_FlyShip_001.001']} position={[-1.902, -0.469, 1.68]} rotation={[-1.58, 0, 1.57]} />
      <mesh geometry={nodes.Object_2003.geometry} material={materials['map_FlyShip_001.001']} position={[-2.25, -1.612, 0.014]} rotation={[-1.58, 0, 1.57]} />
      <mesh geometry={nodes.Object_2004.geometry} material={materials['map_FlyShip_001.001']} position={[-3.786, 0.915, -0.297]} rotation={[-1.58, 0, 1.57]} />
    </group>
  )
}

useGLTF.preload('/model1.glb')
